version: "3.7"

x-env:
  environment: &default-env
    MAIL_MAILER: smtp
    MAIL_HOST: mailhog
    MAIL_PORT: 1025
    MAIL_ENCRYPTION: 0
    REDIS_HOST: redis
    QUEUE_CONNECTION: redis
    SESSION_DRIVER: redis
    DB_CONNECTION: mysql
    DB_HOST: mysql
    DB_PORT: 3306
    DB_DATABASE: homestead
    DB_USERNAME: homestead
    DB_PASSWORD: secret
    APP_NAME: "Exam Papers"
    APP_ENV: local
    APP_KEY: base64:keR1/6nEaaCrtVwYR7e/dh053Sv0AfGUFoNWEgx7XP8=
    APP_DEBUG: 1
    APP_URL: http://examdb.test
    LOG_CHANNEL: stack
    BROADCAST_DRIVER: log
    CACHE_DRIVER: file
    SESSION_LIFETIME: 120
    MAIL_FROM_ADDRESS: someone@example.com
    MAIL_FROM_NAME: "Exam Database"
    PASSWORD_CHECK: 0
    SYSADMIN_EMAIL: someone@glasgow.ac.uk
    FALLBACK_EMAIL: someone@glasgow.ac.uk
    WLM_URI: ""
    LDAP_SERVER: cytosine.campus.gla.ac.uk
    LDAP_OU: Gla
    LDAP_USERNAME: 'your-gla-ldap-admin-username'
    LDAP_PASSWORD: 'your-gla-ldap-admin-password'
    API_KEY: Meewae5emonien8ShueKid8uusocho1iphavao9gae1lahjilohdowehohh5Tho6
    MINIO_KEY: ALIAIOSFODNN7EXAMPLE
    MINIO_SECRET: wPalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    MINIO_REGION: us-east-1
    MINIO_BUCKET: exampapers
    MINIO_ENDPOINT: http://minio:9000

services:
  app:
    image: ${IMAGE_NAME}
    environment:
      CONTAINER_ROLE: app
      <<: *default-env
    ports:
      - "${APP_PORT:-3000}:80"
    depends_on:
      - redis
      - mysql
      - mailhog

  scheduler:
    image: ${IMAGE_NAME}
    environment:
      CONTAINER_ROLE: scheduler
      <<: *default-env
    depends_on:
      - app

  queue:
    image: ${IMAGE_NAME}
    environment:
      CONTAINER_ROLE: queue
      <<: *default-env
    depends_on:
      - app

  migrations:
    image: ${IMAGE_NAME}
    environment:
      CONTAINER_ROLE: migrations
      <<: *default-env
    depends_on:
      - app

  redis:
    image: redis:5.0.4
    volumes:
      - redis:/data

  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  mailhog:
    image: mailhog/mailhog
    ports:
      - "3025:8025"

  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    entrypoint: sh
    command: -c 'mkdir -p /data/exampapers && /usr/bin/minio server /data'
    environment:
      MINIO_ACCESS_KEY: ALIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wPalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_REGION: "us-east-1"
      MINIO_BUCKET: "exampapers"
      MINIO_ENDPOINT: "http://localhost:9000"
    volumes:
      - minio:/data

volumes:
  redis:
    driver: "local"
  mysql:
    driver: "local"
  minio:
    driver: "local"
