version: "3"
services:
  app:
    image: localhost:5000/examdb
    container_name: examdb
    build:
      context: .
      dockerfile: docker/multi.Dockerfile
    depends_on:
      - redis
      - mysql
      - minio
    networks:
      - proxy
      - private
    expose:
      - "80"
    ports:
      - "8088:80"
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: examdb
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      MAIL_HOST: mailhog
      DEFAULT_DISK: images
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_REGION: us-east-1
      MINIO_BUCKET: examdb
      MINIO_ENDPOINT: http://minio:9000
    deploy:
      replicas: 3
      labels:
        - "traefik.backend=examdb"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:examdb.130.209.176.42.xip.io"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.default.protocol=http"

  scheduler:
    image: localhost:5000/examdb
    container_name: jwnc-scheduler
    depends_on:
      - app
    deploy:
      labels:
        - "traefik.enable=false"
    networks:
      - private
    environment:
      APP_ENV: local
      CONTAINER_ROLE: scheduler
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: examdb
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      MAIL_HOST: mailhog
      DEFAULT_DISK: images
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_REGION: us-east-1
      MINIO_BUCKET: examdb
      MINIO_ENDPOINT: http://minio:9000

  queue:
    image: localhost:5000/examdb
    container_name: jwnc-queue
    depends_on:
      - app
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=false"
    networks:
      - private
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: examdb
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      MAIL_HOST: mailhog
      DEFAULT_DISK: images
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_REGION: us-east-1
      MINIO_BUCKET: examdb
      MINIO_ENDPOINT: http://minio:9000

  redis:
    container_name: examdb-redis
    image: redis:4
    deploy:
      labels:
        - "traefik.enable=false"
    networks:
      - private
    volumes:
      - redis:/data

  mysql:
    container_name: jwnc-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      labels:
        - "traefik.enable=false"
    networks:
      - private
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: examdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  minio:
    container_name: examdb-minio
    image: minio/minio
    command: server /data
    networks:
      - proxy
      - private
    deploy:
      labels:
        - "traefik.backend=examdb-minio"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:examdb.130.209.176.42.xip.io;PathPrefixStrip:/images"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.default.protocol=http"
    expose:
      - "9000"
    volumes:
      - minio:/data
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

  minio-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb myminio/examdb;
      /usr/bin/mc policy download myminio/examdb;
      exit 0;
      "

  mailhog:
    container_name: examdb-mailhog
    image: mailhog/mailhog
    deploy:
      labels:
        - "traefik.backend=examdb-mailhog"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:examdb.130.209.176.42.xip.io;PathPrefixStrip:/mailhog"
        - "traefik.enable=true"
        - "traefik.port=8025"
        - "traefik.default.protocol=http"
    expose:
      - "8025"
    networks:
      - proxy
      - private

volumes:
  redis:
    driver: "local"
  mysql:
    driver: "local"
  minio:
    driver: "local"

networks:
  private:
  proxy:
    external: true
