apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  namespace: ${NAMESPACE}
  labels:
    app: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - image: ${IMAGE_NAME}
        name: queue
        env:
        - name: APP_ROLE
          value: queue
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - php /var/www/html/artisan horizon:status | grep -q 'Horizon is running'
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - php /var/www/html/artisan horizon:status | grep -q 'Horizon is running'
          initialDelaySeconds: 5
          periodSeconds: 3
