name: build-images

on:
  # push:
  workflow_dispatch:

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          target: prod
          build-args: |
            PHP_VERSION=7.4
          tags: |
            uogsoe/${{ github.event.repository.name }}:${{ github.sha }}
  tests:
      runs-on: ubuntu-latest
      services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_ROOT_PASSWORD: homestead
            MYSQL_DATABASE: homestead
          ports:
            - 33306:3306
      steps:
        - name: Run PHPUnit
          env:
            DB_HOST: mysql
            DB_USERNAME: root
            DB_PASSWORD: homestead
            DB_DATABASE: homestead
            DB_CONNECTION: mysql
          with:
            tags: |
              uogsoe/${{ github.event.repository.name }}:${{ github.sha }}
